server:
  port: <Server-Port>

spring:
  application:
    name: Restaurant Management System
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: <DB-Url>
    driverClassName: <DB-Driver>
    username: <DB-Username>
    password: <DB-Password>
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
