server:
  port: 8080

spring:
  application:
    name: Restaurant Management System
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:./data/rms
    driverClassName: org.h2.Driver
    username: genius
    password: genius123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

